// Code generated by go generate; DO NOT EDIT.
// This file was generated by stream_dupn_gen.go at 2021-06-18 18:30:33.499139 +0000 UTC
package flow

func (s *Stream) Dup2(chBuf int) (*Stream, *Stream) {
	outs := s.DupN(chBuf, 2)
	return outs[0], outs[1]
}

func (s *Stream) Dup3(chBuf int) (*Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 3)
	return outs[0], outs[1], outs[2]
}

func (s *Stream) Dup4(chBuf int) (*Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 4)
	return outs[0], outs[1], outs[2], outs[3]
}

func (s *Stream) Dup5(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 5)
	return outs[0], outs[1], outs[2], outs[3], outs[4]
}

func (s *Stream) Dup6(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 6)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5]
}

func (s *Stream) Dup7(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 7)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6]
}

func (s *Stream) Dup8(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 8)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7]
}

func (s *Stream) Dup9(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 9)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8]
}

func (s *Stream) Dup10(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 10)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9]
}

func (s *Stream) Dup11(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 11)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10]
}

func (s *Stream) Dup12(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 12)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10], outs[11]
}

func (s *Stream) Dup13(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 13)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10], outs[11], outs[12]
}

func (s *Stream) Dup14(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 14)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10], outs[11], outs[12], outs[13]
}

func (s *Stream) Dup15(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 15)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10], outs[11], outs[12], outs[13], outs[14]
}

func (s *Stream) Dup16(chBuf int) (*Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream, *Stream) {
	outs := s.DupN(chBuf, 16)
	return outs[0], outs[1], outs[2], outs[3], outs[4], outs[5], outs[6], outs[7], outs[8], outs[9], outs[10], outs[11], outs[12], outs[13], outs[14], outs[15]
}

